image: ruby:2.6.1

pipelines:
  default:
    - step:
        script:
            - curl https://cli-assets.heroku.com/install.sh | sh
    - step:
        deployment: test
        caches:
          - bundler
        script:
          - heroku auth:token
          - apt-get update && apt-get install -y build-essential libpq-dev nodejs
          - bundle install
          - bundle exec rails db:setup RAILS_ENV=test
          - bundle exec rails db:test:prepare RAILS_ENV=test
          - bundle exec rspec
        services:
          - database
definitions:
  services:
    database:
      image: postgres
  caches:
    bundler: ./vendor