image: ruby:2.6.1

pipelines:
  default:
    - step:
        deployment: staging
        caches:
          - bundler
        script:
          - apt-get update && apt-get install -y build-essential libpq-dev nodejs
          - curl https://cli-assets.heroku.com/install.sh | sh
          - heroku git:remote -a portal-agro
          - git remote -v
          - cat ~/.netrc
          - heroku run rails db:migrate
        services:
          - database
definitions:
  services:
    database:
      image: postgres
  caches:
    bundler: ./vendor