image: ruby:2.6.1

pipelines:
  default:
    - step:
        script:
          - pipe: atlassian/heroku-deploy:0.1.1
            variables:
              HEROKU_API_KEY: '30824f32-76ac-4d92-b023-d1582f5e6b40'
              HEROKU_APP_NAME: 'portal-agro'
              ZIP_FILE: 'porta-agro.tar.gz'
    - step:
        deployment: test
        caches:
          - bundler
        script:
          - heroku auth:token
          - apt-get update && apt-get install -y build-essential libpq-dev nodejs
          - bundle install
          - bundle exec rails db:setup RAILS_ENV=test
          - bundle exec rails db:test:prepare RAILS_ENV=test
          - bundle exec rspec
        services:
          - database
definitions:
  services:
    database:
      image: postgres
  caches:
    bundler: ./vendor