development:
  adapter: postgresql
  encoding: unicode
  database: portal_agro_development
  host: db
  port: 5432
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: portal_agro_test
  host: db
  port: 5432
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: portal_agro_production
  host: db
  port: 5432
  pool: 5
  username: postgres
  password: postgres

