production:
  adapter: postgresql
  encoding: unicode
  database: portal_agro_production
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  adapter: postgresql
  encoding: unicode
  database: portal_agro_development
  host: db
  port: 5432
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: portal_agro_test
  host: db
  port: 5432
  pool: 5
  username: postgres
  password: postgres

